/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule aaAppQuery.graphql
 * @generated SignedSource<<939acd9bdd04e896d26d46e3bf09053b>>
 * @relayHash 7c458c0e9f0f6fcc9fcde36a5f3fc387
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/

/* eslint-disable comma-dangle, quotes */

/*
query aaAppQuery {
  viewer {
    ...adTranslator_viewer
    ...aeSettings_viewer
    id
  }
}

fragment adTranslator_viewer on Viewer {
  id
  config {
    langs
    id
  }
  keys(first: 100000) {
    edges {
      node {
        id
        unusedSince
        context
        text
        ...edTranslatorRow_theKey
        translations(first: 100000) {
          edges {
            node {
              lang
              id
            }
          }
        }
      }
    }
  }
  ...edTranslatorRow_viewer
}

fragment aeSettings_viewer on Viewer {
  id
  config {
    langs
    srcPaths
    srcExtensions
    msgFunctionNames
    msgRegexps
    fMinify
    fJsOutput
    fJsonOutput
    fReactIntlOutput
    id
  }
}

fragment edTranslatorRow_theKey on Key {
  id
  context
  text
  unusedSince
  ...eeTranslation_theKey
  translations(first: 100000) {
    edges {
      node {
        id
        lang
        ...eeTranslation_translation
      }
    }
  }
}

fragment edTranslatorRow_viewer on Viewer {
  id
}

fragment eeTranslation_theKey on Key {
  id
  text
}

fragment eeTranslation_translation on Translation {
  id
  lang
  translation
  fuzzy
}
*/

const batch /*: ConcreteBatch*/ = {
  fragment: {
    argumentDefinitions: [],
    kind: 'Fragment',
    metadata: null,
    name: 'aaAppQuery',
    selections: [
      {
        kind: 'LinkedField',
        alias: 'viewer',
        args: null,
        concreteType: 'Viewer',
        name: '__viewer_viewer',
        plural: false,
        selections: [
          {
            kind: 'FragmentSpread',
            name: 'adTranslator_viewer',
            args: null,
          },
          {
            kind: 'FragmentSpread',
            name: 'aeSettings_viewer',
            args: null,
          },
        ],
        storageKey: null,
      },
    ],
    type: 'Query',
  },
  id: null,
  kind: 'Batch',
  metadata: {},
  name: 'aaAppQuery',
  query: {
    argumentDefinitions: [],
    kind: 'Root',
    name: 'aaAppQuery',
    operation: 'query',
    selections: [
      {
        kind: 'LinkedField',
        alias: null,
        args: null,
        concreteType: 'Viewer',
        name: 'viewer',
        plural: false,
        selections: [
          {
            kind: 'ScalarField',
            alias: null,
            args: null,
            name: 'id',
            storageKey: null,
          },
          {
            kind: 'LinkedField',
            alias: null,
            args: null,
            concreteType: 'Config',
            name: 'config',
            plural: false,
            selections: [
              {
                kind: 'ScalarField',
                alias: null,
                args: null,
                name: 'langs',
                storageKey: null,
              },
              {
                kind: 'ScalarField',
                alias: null,
                args: null,
                name: 'id',
                storageKey: null,
              },
              {
                kind: 'ScalarField',
                alias: null,
                args: null,
                name: 'srcPaths',
                storageKey: null,
              },
              {
                kind: 'ScalarField',
                alias: null,
                args: null,
                name: 'srcExtensions',
                storageKey: null,
              },
              {
                kind: 'ScalarField',
                alias: null,
                args: null,
                name: 'msgFunctionNames',
                storageKey: null,
              },
              {
                kind: 'ScalarField',
                alias: null,
                args: null,
                name: 'msgRegexps',
                storageKey: null,
              },
              {
                kind: 'ScalarField',
                alias: null,
                args: null,
                name: 'fMinify',
                storageKey: null,
              },
              {
                kind: 'ScalarField',
                alias: null,
                args: null,
                name: 'fJsOutput',
                storageKey: null,
              },
              {
                kind: 'ScalarField',
                alias: null,
                args: null,
                name: 'fJsonOutput',
                storageKey: null,
              },
              {
                kind: 'ScalarField',
                alias: null,
                args: null,
                name: 'fReactIntlOutput',
                storageKey: null,
              },
            ],
            storageKey: null,
          },
          {
            kind: 'LinkedField',
            alias: null,
            args: [
              {
                kind: 'Literal',
                name: 'first',
                value: 100000,
                type: 'Int',
              },
            ],
            concreteType: 'KeyConnection',
            name: 'keys',
            plural: false,
            selections: [
              {
                kind: 'LinkedField',
                alias: null,
                args: null,
                concreteType: 'KeyEdge',
                name: 'edges',
                plural: true,
                selections: [
                  {
                    kind: 'LinkedField',
                    alias: null,
                    args: null,
                    concreteType: 'Key',
                    name: 'node',
                    plural: false,
                    selections: [
                      {
                        kind: 'ScalarField',
                        alias: null,
                        args: null,
                        name: 'id',
                        storageKey: null,
                      },
                      {
                        kind: 'ScalarField',
                        alias: null,
                        args: null,
                        name: 'unusedSince',
                        storageKey: null,
                      },
                      {
                        kind: 'ScalarField',
                        alias: null,
                        args: null,
                        name: 'context',
                        storageKey: null,
                      },
                      {
                        kind: 'ScalarField',
                        alias: null,
                        args: null,
                        name: 'text',
                        storageKey: null,
                      },
                      {
                        kind: 'LinkedField',
                        alias: null,
                        args: [
                          {
                            kind: 'Literal',
                            name: 'first',
                            value: 100000,
                            type: 'Int',
                          },
                        ],
                        concreteType: 'TranslationConnection',
                        name: 'translations',
                        plural: false,
                        selections: [
                          {
                            kind: 'LinkedField',
                            alias: null,
                            args: null,
                            concreteType: 'TranslationEdge',
                            name: 'edges',
                            plural: true,
                            selections: [
                              {
                                kind: 'LinkedField',
                                alias: null,
                                args: null,
                                concreteType: 'Translation',
                                name: 'node',
                                plural: false,
                                selections: [
                                  {
                                    kind: 'ScalarField',
                                    alias: null,
                                    args: null,
                                    name: 'id',
                                    storageKey: null,
                                  },
                                  {
                                    kind: 'ScalarField',
                                    alias: null,
                                    args: null,
                                    name: 'lang',
                                    storageKey: null,
                                  },
                                  {
                                    kind: 'ScalarField',
                                    alias: null,
                                    args: null,
                                    name: 'translation',
                                    storageKey: null,
                                  },
                                  {
                                    kind: 'ScalarField',
                                    alias: null,
                                    args: null,
                                    name: 'fuzzy',
                                    storageKey: null,
                                  },
                                ],
                                storageKey: null,
                              },
                            ],
                            storageKey: null,
                          },
                        ],
                        storageKey: 'translations{"first":100000}',
                      },
                    ],
                    storageKey: null,
                  },
                ],
                storageKey: null,
              },
            ],
            storageKey: 'keys{"first":100000}',
          },
        ],
        storageKey: null,
      },
      {
        kind: 'LinkedHandle',
        alias: null,
        args: null,
        handle: 'viewer',
        name: 'viewer',
        key: '',
        filters: null,
      },
    ],
  },
  text:
    'query aaAppQuery {\n  viewer {\n    ...adTranslator_viewer\n    ...aeSettings_viewer\n    id\n  }\n}\n\nfragment adTranslator_viewer on Viewer {\n  id\n  config {\n    langs\n    id\n  }\n  keys(first: 100000) {\n    edges {\n      node {\n        id\n        unusedSince\n        context\n        text\n        ...edTranslatorRow_theKey\n        translations(first: 100000) {\n          edges {\n            node {\n              lang\n              id\n            }\n          }\n        }\n      }\n    }\n  }\n  ...edTranslatorRow_viewer\n}\n\nfragment aeSettings_viewer on Viewer {\n  id\n  config {\n    langs\n    srcPaths\n    srcExtensions\n    msgFunctionNames\n    msgRegexps\n    fMinify\n    fJsOutput\n    fJsonOutput\n    fReactIntlOutput\n    id\n  }\n}\n\nfragment edTranslatorRow_theKey on Key {\n  id\n  context\n  text\n  unusedSince\n  ...eeTranslation_theKey\n  translations(first: 100000) {\n    edges {\n      node {\n        id\n        lang\n        ...eeTranslation_translation\n      }\n    }\n  }\n}\n\nfragment edTranslatorRow_viewer on Viewer {\n  id\n}\n\nfragment eeTranslation_theKey on Key {\n  id\n  text\n}\n\nfragment eeTranslation_translation on Translation {\n  id\n  lang\n  translation\n  fuzzy\n}\n',
};

module.exports = batch;
