/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule aeSettings_viewer.graphql
 * @generated SignedSource<<1c740dcf75d2de338436bc48d6de156d>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type aeSettings_viewer = {
  id: string;
  config?: ?aeSettings_viewer_config;
};

export type aeSettings_viewer_config = {
  langs?: ?Array<?string>;
  srcPaths?: ?Array<?string>;
  srcExtensions?: ?Array<?string>;
  msgFunctionNames?: ?Array<?string>;
  msgRegexps?: ?Array<?string>;
  fMinify?: ?boolean;
  fJsOutput?: ?boolean;
  fJsonOutput?: ?boolean;
  fReactIntlOutput?: ?boolean;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "aeSettings_viewer",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "args": null,
      "concreteType": "Config",
      "name": "config",
      "plural": false,
      "selections": [
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "langs",
          "storageKey": null
        },
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "srcPaths",
          "storageKey": null
        },
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "srcExtensions",
          "storageKey": null
        },
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "msgFunctionNames",
          "storageKey": null
        },
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "msgRegexps",
          "storageKey": null
        },
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "fMinify",
          "storageKey": null
        },
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "fJsOutput",
          "storageKey": null
        },
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "fJsonOutput",
          "storageKey": null
        },
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "fReactIntlOutput",
          "storageKey": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "Viewer"
};

module.exports = fragment;
