/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule edTranslatorRow_viewer.graphql
 * @generated SignedSource<<ec2c0123e73c256238e1a5116f8ee18e>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type edTranslatorRow_viewer = {
  id: string;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "edTranslatorRow_viewer",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    }
  ],
  "type": "Viewer"
};

module.exports = fragment;
