/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule eeTranslation_theKey.graphql
 * @generated SignedSource<<bd803ac63ef667dc4b4ff1c3ab006966>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type eeTranslation_theKey = {
  id: string;
  text?: ?string;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "eeTranslation_theKey",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "text",
      "storageKey": null
    }
  ],
  "type": "Key"
};

module.exports = fragment;
