/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule translator_viewer.graphql
 * @generated SignedSource<<ec83f814cbe463d82531a959ddd603ed>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type translator_viewer = {
  id: string;
  config?: ?translator_viewer_config;
  keys?: ?translator_viewer_keys;
};

export type translator_viewer_config = {
  langs?: ?Array<?string>;
};

export type translator_viewer_keys_edges_node_translations_edges_node = {
  lang?: ?string;
};

export type translator_viewer_keys_edges_node_translations_edges = {
  node?: ?translator_viewer_keys_edges_node_translations_edges_node;
};

export type translator_viewer_keys_edges_node_translations = {
  edges?: ?Array<?translator_viewer_keys_edges_node_translations_edges>;
};

export type translator_viewer_keys_edges_node = {
  id: string;
  unusedSince?: ?string;
  context?: ?string;
  text?: ?string;
  translations?: ?translator_viewer_keys_edges_node_translations;
};

export type translator_viewer_keys_edges = {
  node?: ?translator_viewer_keys_edges_node;
};

export type translator_viewer_keys = {
  edges?: ?Array<?translator_viewer_keys_edges>;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "translator_viewer",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "args": null,
      "concreteType": "Config",
      "name": "config",
      "plural": false,
      "selections": [
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "langs",
          "storageKey": null
        }
      ],
      "storageKey": null
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "args": [
        {
          "kind": "Literal",
          "name": "first",
          "value": 100000,
          "type": "Int"
        }
      ],
      "concreteType": "KeyConnection",
      "name": "keys",
      "plural": false,
      "selections": [
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "KeyEdge",
          "name": "edges",
          "plural": true,
          "selections": [
            {
              "kind": "LinkedField",
              "alias": null,
              "args": null,
              "concreteType": "Key",
              "name": "node",
              "plural": false,
              "selections": [
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "id",
                  "storageKey": null
                },
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "unusedSince",
                  "storageKey": null
                },
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "context",
                  "storageKey": null
                },
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "text",
                  "storageKey": null
                },
                {
                  "kind": "FragmentSpread",
                  "name": "translatorRow_theKey",
                  "args": null
                },
                {
                  "kind": "LinkedField",
                  "alias": null,
                  "args": [
                    {
                      "kind": "Literal",
                      "name": "first",
                      "value": 100000,
                      "type": "Int"
                    }
                  ],
                  "concreteType": "TranslationConnection",
                  "name": "translations",
                  "plural": false,
                  "selections": [
                    {
                      "kind": "LinkedField",
                      "alias": null,
                      "args": null,
                      "concreteType": "TranslationEdge",
                      "name": "edges",
                      "plural": true,
                      "selections": [
                        {
                          "kind": "LinkedField",
                          "alias": null,
                          "args": null,
                          "concreteType": "Translation",
                          "name": "node",
                          "plural": false,
                          "selections": [
                            {
                              "kind": "ScalarField",
                              "alias": null,
                              "args": null,
                              "name": "lang",
                              "storageKey": null
                            }
                          ],
                          "storageKey": null
                        }
                      ],
                      "storageKey": null
                    }
                  ],
                  "storageKey": "translations{\"first\":100000}"
                }
              ],
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ],
      "storageKey": "keys{\"first\":100000}"
    },
    {
      "kind": "FragmentSpread",
      "name": "translatorRow_viewer",
      "args": null
    }
  ],
  "type": "Viewer"
};

module.exports = fragment;
