/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule translatorRow_theKey.graphql
 * @generated SignedSource<<514b4f637a71a5ab805e0ea090a492e4>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type translatorRow_theKey = {
  id: string;
  context?: ?string;
  text?: ?string;
  unusedSince?: ?string;
  translations?: ?translatorRow_theKey_translations;
};

export type translatorRow_theKey_translations_edges_node = {
  id: string;
  lang?: ?string;
};

export type translatorRow_theKey_translations_edges = {
  node?: ?translatorRow_theKey_translations_edges_node;
};

export type translatorRow_theKey_translations = {
  edges?: ?Array<?translatorRow_theKey_translations_edges>;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "translatorRow_theKey",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "context",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "text",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "unusedSince",
      "storageKey": null
    },
    {
      "kind": "FragmentSpread",
      "name": "translation_theKey",
      "args": null
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "args": [
        {
          "kind": "Literal",
          "name": "first",
          "value": 100000,
          "type": "Int"
        }
      ],
      "concreteType": "TranslationConnection",
      "name": "translations",
      "plural": false,
      "selections": [
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "TranslationEdge",
          "name": "edges",
          "plural": true,
          "selections": [
            {
              "kind": "LinkedField",
              "alias": null,
              "args": null,
              "concreteType": "Translation",
              "name": "node",
              "plural": false,
              "selections": [
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "id",
                  "storageKey": null
                },
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "lang",
                  "storageKey": null
                },
                {
                  "kind": "FragmentSpread",
                  "name": "translation_translation",
                  "args": null
                }
              ],
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ],
      "storageKey": "translations{\"first\":100000}"
    }
  ],
  "type": "Key"
};

module.exports = fragment;
