/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule translation_theKey.graphql
 * @generated SignedSource<<f8eac49a7ddf6e3a13be076113ae1b40>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type translation_theKey = {
  id: string;
  text?: ?string;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "translation_theKey",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "text",
      "storageKey": null
    }
  ],
  "type": "Key"
};

module.exports = fragment;
