/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule translation_translation.graphql
 * @generated SignedSource<<c6723f6bab890a7802e77438fc979931>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type translation_translation = {
  id: string;
  lang?: ?string;
  translation?: ?string;
  fuzzy?: ?boolean;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "translation_translation",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "lang",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "translation",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "fuzzy",
      "storageKey": null
    }
  ],
  "type": "Translation"
};

module.exports = fragment;
