// flow-typed signature: 456cc221c09af6c7efcc5c905b2d18dd
// flow-typed version: <<STUB>>/babel-loader_v6.2.5/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-loader/lib/fs-cache' {
  declare module.exports: any;
}

declare module 'babel-loader/lib/helpers/exists' {
  declare module.exports: any;
}

declare module 'babel-loader/lib/helpers/read' {
  declare module.exports: any;
}

declare module 'babel-loader/lib/resolve-rc' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-loader/index' {
  declare module.exports: $Exports<'babel-loader'>;
}
declare module 'babel-loader/index.js' {
  declare module.exports: $Exports<'babel-loader'>;
}
declare module 'babel-loader/lib/fs-cache.js' {
  declare module.exports: $Exports<'babel-loader/lib/fs-cache'>;
}
declare module 'babel-loader/lib/helpers/exists.js' {
  declare module.exports: $Exports<'babel-loader/lib/helpers/exists'>;
}
declare module 'babel-loader/lib/helpers/read.js' {
  declare module.exports: $Exports<'babel-loader/lib/helpers/read'>;
}
declare module 'babel-loader/lib/resolve-rc.js' {
  declare module.exports: $Exports<'babel-loader/lib/resolve-rc'>;
}
