// flow-typed signature: 83e247f8a83669eae7f4c9a80fb0659e
// flow-typed version: <<STUB>>/diveSync_v0.3.0/flow_v0.32.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'diveSync'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'diveSync' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'diveSync/diveSync' {
  declare module.exports: any;
}

declare module 'diveSync/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'diveSync/diveSync.js' {
  declare module.exports: $Exports<'diveSync/diveSync'>;
}
declare module 'diveSync/test/test.js' {
  declare module.exports: $Exports<'diveSync/test/test'>;
}
