// flow-typed signature: 4b29826528f2352751c617cc39666b04
// flow-typed version: <<STUB>>/giu_v0.8.1/flow_v0.32.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'giu'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'giu' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'giu/examples/demo1-common' {
  declare module.exports: any;
}

declare module 'giu/examples/demo1-dataTables' {
  declare module.exports: any;
}

declare module 'giu/examples/demo1-forms' {
  declare module.exports: any;
}

declare module 'giu/examples/demo1-hints' {
  declare module.exports: any;
}

declare module 'giu/examples/demo1-modals' {
  declare module.exports: any;
}

declare module 'giu/examples/demo1' {
  declare module.exports: any;
}

declare module 'giu/examples/extractInlineDocs' {
  declare module.exports: any;
}

declare module 'giu/examples/index' {
  declare module.exports: any;
}

declare module 'giu/examples/server' {
  declare module.exports: any;
}

declare module 'giu/examples/webpackConfig' {
  declare module.exports: any;
}

declare module 'giu/lib/components/backdrop' {
  declare module.exports: any;
}

declare module 'giu/lib/components/button' {
  declare module.exports: any;
}

declare module 'giu/lib/components/dataTable' {
  declare module.exports: any;
}

declare module 'giu/lib/components/dataTableRow' {
  declare module.exports: any;
}

declare module 'giu/lib/components/dropDownMenu' {
  declare module.exports: any;
}

declare module 'giu/lib/components/floats' {
  declare module.exports: any;
}

declare module 'giu/lib/components/focusCapture' {
  declare module.exports: any;
}

declare module 'giu/lib/components/hintArrow' {
  declare module.exports: any;
}

declare module 'giu/lib/components/hintLabel' {
  declare module.exports: any;
}

declare module 'giu/lib/components/hints' {
  declare module.exports: any;
}

declare module 'giu/lib/components/hintScreen' {
  declare module.exports: any;
}

declare module 'giu/lib/components/icon' {
  declare module.exports: any;
}

declare module 'giu/lib/components/largeMessage' {
  declare module.exports: any;
}

declare module 'giu/lib/components/modal' {
  declare module.exports: any;
}

declare module 'giu/lib/components/modals' {
  declare module.exports: any;
}

declare module 'giu/lib/components/notification' {
  declare module.exports: any;
}

declare module 'giu/lib/components/notifications' {
  declare module.exports: any;
}

declare module 'giu/lib/components/progress' {
  declare module.exports: any;
}

declare module 'giu/lib/components/spinner' {
  declare module.exports: any;
}

declare module 'giu/lib/components/verticalManager' {
  declare module.exports: any;
}

declare module 'giu/lib/components/virtualScroller' {
  declare module.exports: any;
}

declare module 'giu/lib/gral/constants' {
  declare module.exports: any;
}

declare module 'giu/lib/gral/dates' {
  declare module.exports: any;
}

declare module 'giu/lib/gral/helpers' {
  declare module.exports: any;
}

declare module 'giu/lib/gral/keys' {
  declare module.exports: any;
}

declare module 'giu/lib/gral/math' {
  declare module.exports: any;
}

declare module 'giu/lib/gral/storage' {
  declare module.exports: any;
}

declare module 'giu/lib/gral/styles' {
  declare module.exports: any;
}

declare module 'giu/lib/gral/validators' {
  declare module.exports: any;
}

declare module 'giu/lib/gral/visibility' {
  declare module.exports: any;
}

declare module 'giu/lib/hocs/hoverable' {
  declare module.exports: any;
}

declare module 'giu/lib/hocs/input' {
  declare module.exports: any;
}

declare module 'giu/lib/index' {
  declare module.exports: any;
}

declare module 'giu/lib/inputs/checkbox' {
  declare module.exports: any;
}

declare module 'giu/lib/inputs/colorInput' {
  declare module.exports: any;
}

declare module 'giu/lib/inputs/colorPicker' {
  declare module.exports: any;
}

declare module 'giu/lib/inputs/dateInput' {
  declare module.exports: any;
}

declare module 'giu/lib/inputs/datePicker' {
  declare module.exports: any;
}

declare module 'giu/lib/inputs/dateTimePicker' {
  declare module.exports: any;
}

declare module 'giu/lib/inputs/fileInput' {
  declare module.exports: any;
}

declare module 'giu/lib/inputs/iosFloatWrapper' {
  declare module.exports: any;
}

declare module 'giu/lib/inputs/listPicker' {
  declare module.exports: any;
}

declare module 'giu/lib/inputs/radioGroup' {
  declare module.exports: any;
}

declare module 'giu/lib/inputs/select' {
  declare module.exports: any;
}

declare module 'giu/lib/inputs/selectCustom' {
  declare module.exports: any;
}

declare module 'giu/lib/inputs/selectNative' {
  declare module.exports: any;
}

declare module 'giu/lib/inputs/textarea' {
  declare module.exports: any;
}

declare module 'giu/lib/inputs/textNumberRangeInput' {
  declare module.exports: any;
}

declare module 'giu/lib/inputs/timePickerAnalog' {
  declare module.exports: any;
}

declare module 'giu/lib/inputs/timePickerDigital' {
  declare module.exports: any;
}

declare module 'giu/libEs6/components/backdrop' {
  declare module.exports: any;
}

declare module 'giu/libEs6/components/button' {
  declare module.exports: any;
}

declare module 'giu/libEs6/components/dataTable' {
  declare module.exports: any;
}

declare module 'giu/libEs6/components/dataTableRow' {
  declare module.exports: any;
}

declare module 'giu/libEs6/components/dropDownMenu' {
  declare module.exports: any;
}

declare module 'giu/libEs6/components/floats' {
  declare module.exports: any;
}

declare module 'giu/libEs6/components/focusCapture' {
  declare module.exports: any;
}

declare module 'giu/libEs6/components/hintArrow' {
  declare module.exports: any;
}

declare module 'giu/libEs6/components/hintLabel' {
  declare module.exports: any;
}

declare module 'giu/libEs6/components/hints' {
  declare module.exports: any;
}

declare module 'giu/libEs6/components/hintScreen' {
  declare module.exports: any;
}

declare module 'giu/libEs6/components/icon' {
  declare module.exports: any;
}

declare module 'giu/libEs6/components/largeMessage' {
  declare module.exports: any;
}

declare module 'giu/libEs6/components/modal' {
  declare module.exports: any;
}

declare module 'giu/libEs6/components/modals' {
  declare module.exports: any;
}

declare module 'giu/libEs6/components/notification' {
  declare module.exports: any;
}

declare module 'giu/libEs6/components/notifications' {
  declare module.exports: any;
}

declare module 'giu/libEs6/components/progress' {
  declare module.exports: any;
}

declare module 'giu/libEs6/components/spinner' {
  declare module.exports: any;
}

declare module 'giu/libEs6/components/verticalManager' {
  declare module.exports: any;
}

declare module 'giu/libEs6/components/virtualScroller' {
  declare module.exports: any;
}

declare module 'giu/libEs6/gral/constants' {
  declare module.exports: any;
}

declare module 'giu/libEs6/gral/dates' {
  declare module.exports: any;
}

declare module 'giu/libEs6/gral/helpers' {
  declare module.exports: any;
}

declare module 'giu/libEs6/gral/keys' {
  declare module.exports: any;
}

declare module 'giu/libEs6/gral/math' {
  declare module.exports: any;
}

declare module 'giu/libEs6/gral/storage' {
  declare module.exports: any;
}

declare module 'giu/libEs6/gral/styles' {
  declare module.exports: any;
}

declare module 'giu/libEs6/gral/validators' {
  declare module.exports: any;
}

declare module 'giu/libEs6/gral/visibility' {
  declare module.exports: any;
}

declare module 'giu/libEs6/hocs/hoverable' {
  declare module.exports: any;
}

declare module 'giu/libEs6/hocs/input' {
  declare module.exports: any;
}

declare module 'giu/libEs6/index' {
  declare module.exports: any;
}

declare module 'giu/libEs6/inputs/checkbox' {
  declare module.exports: any;
}

declare module 'giu/libEs6/inputs/colorInput' {
  declare module.exports: any;
}

declare module 'giu/libEs6/inputs/colorPicker' {
  declare module.exports: any;
}

declare module 'giu/libEs6/inputs/dateInput' {
  declare module.exports: any;
}

declare module 'giu/libEs6/inputs/datePicker' {
  declare module.exports: any;
}

declare module 'giu/libEs6/inputs/dateTimePicker' {
  declare module.exports: any;
}

declare module 'giu/libEs6/inputs/fileInput' {
  declare module.exports: any;
}

declare module 'giu/libEs6/inputs/iosFloatWrapper' {
  declare module.exports: any;
}

declare module 'giu/libEs6/inputs/listPicker' {
  declare module.exports: any;
}

declare module 'giu/libEs6/inputs/radioGroup' {
  declare module.exports: any;
}

declare module 'giu/libEs6/inputs/select' {
  declare module.exports: any;
}

declare module 'giu/libEs6/inputs/selectCustom' {
  declare module.exports: any;
}

declare module 'giu/libEs6/inputs/selectNative' {
  declare module.exports: any;
}

declare module 'giu/libEs6/inputs/textarea' {
  declare module.exports: any;
}

declare module 'giu/libEs6/inputs/textNumberRangeInput' {
  declare module.exports: any;
}

declare module 'giu/libEs6/inputs/timePickerAnalog' {
  declare module.exports: any;
}

declare module 'giu/libEs6/inputs/timePickerDigital' {
  declare module.exports: any;
}

// Filename aliases
declare module 'giu/examples/demo1-common.js' {
  declare module.exports: $Exports<'giu/examples/demo1-common'>;
}
declare module 'giu/examples/demo1-dataTables.js' {
  declare module.exports: $Exports<'giu/examples/demo1-dataTables'>;
}
declare module 'giu/examples/demo1-forms.js' {
  declare module.exports: $Exports<'giu/examples/demo1-forms'>;
}
declare module 'giu/examples/demo1-hints.js' {
  declare module.exports: $Exports<'giu/examples/demo1-hints'>;
}
declare module 'giu/examples/demo1-modals.js' {
  declare module.exports: $Exports<'giu/examples/demo1-modals'>;
}
declare module 'giu/examples/demo1.js' {
  declare module.exports: $Exports<'giu/examples/demo1'>;
}
declare module 'giu/examples/extractInlineDocs.js' {
  declare module.exports: $Exports<'giu/examples/extractInlineDocs'>;
}
declare module 'giu/examples/index.js' {
  declare module.exports: $Exports<'giu/examples/index'>;
}
declare module 'giu/examples/server.js' {
  declare module.exports: $Exports<'giu/examples/server'>;
}
declare module 'giu/examples/webpackConfig.js' {
  declare module.exports: $Exports<'giu/examples/webpackConfig'>;
}
declare module 'giu/lib/components/backdrop.js' {
  declare module.exports: $Exports<'giu/lib/components/backdrop'>;
}
declare module 'giu/lib/components/button.js' {
  declare module.exports: $Exports<'giu/lib/components/button'>;
}
declare module 'giu/lib/components/dataTable.js' {
  declare module.exports: $Exports<'giu/lib/components/dataTable'>;
}
declare module 'giu/lib/components/dataTableRow.js' {
  declare module.exports: $Exports<'giu/lib/components/dataTableRow'>;
}
declare module 'giu/lib/components/dropDownMenu.js' {
  declare module.exports: $Exports<'giu/lib/components/dropDownMenu'>;
}
declare module 'giu/lib/components/floats.js' {
  declare module.exports: $Exports<'giu/lib/components/floats'>;
}
declare module 'giu/lib/components/focusCapture.js' {
  declare module.exports: $Exports<'giu/lib/components/focusCapture'>;
}
declare module 'giu/lib/components/hintArrow.js' {
  declare module.exports: $Exports<'giu/lib/components/hintArrow'>;
}
declare module 'giu/lib/components/hintLabel.js' {
  declare module.exports: $Exports<'giu/lib/components/hintLabel'>;
}
declare module 'giu/lib/components/hints.js' {
  declare module.exports: $Exports<'giu/lib/components/hints'>;
}
declare module 'giu/lib/components/hintScreen.js' {
  declare module.exports: $Exports<'giu/lib/components/hintScreen'>;
}
declare module 'giu/lib/components/icon.js' {
  declare module.exports: $Exports<'giu/lib/components/icon'>;
}
declare module 'giu/lib/components/largeMessage.js' {
  declare module.exports: $Exports<'giu/lib/components/largeMessage'>;
}
declare module 'giu/lib/components/modal.js' {
  declare module.exports: $Exports<'giu/lib/components/modal'>;
}
declare module 'giu/lib/components/modals.js' {
  declare module.exports: $Exports<'giu/lib/components/modals'>;
}
declare module 'giu/lib/components/notification.js' {
  declare module.exports: $Exports<'giu/lib/components/notification'>;
}
declare module 'giu/lib/components/notifications.js' {
  declare module.exports: $Exports<'giu/lib/components/notifications'>;
}
declare module 'giu/lib/components/progress.js' {
  declare module.exports: $Exports<'giu/lib/components/progress'>;
}
declare module 'giu/lib/components/spinner.js' {
  declare module.exports: $Exports<'giu/lib/components/spinner'>;
}
declare module 'giu/lib/components/verticalManager.js' {
  declare module.exports: $Exports<'giu/lib/components/verticalManager'>;
}
declare module 'giu/lib/components/virtualScroller.js' {
  declare module.exports: $Exports<'giu/lib/components/virtualScroller'>;
}
declare module 'giu/lib/gral/constants.js' {
  declare module.exports: $Exports<'giu/lib/gral/constants'>;
}
declare module 'giu/lib/gral/dates.js' {
  declare module.exports: $Exports<'giu/lib/gral/dates'>;
}
declare module 'giu/lib/gral/helpers.js' {
  declare module.exports: $Exports<'giu/lib/gral/helpers'>;
}
declare module 'giu/lib/gral/keys.js' {
  declare module.exports: $Exports<'giu/lib/gral/keys'>;
}
declare module 'giu/lib/gral/math.js' {
  declare module.exports: $Exports<'giu/lib/gral/math'>;
}
declare module 'giu/lib/gral/storage.js' {
  declare module.exports: $Exports<'giu/lib/gral/storage'>;
}
declare module 'giu/lib/gral/styles.js' {
  declare module.exports: $Exports<'giu/lib/gral/styles'>;
}
declare module 'giu/lib/gral/validators.js' {
  declare module.exports: $Exports<'giu/lib/gral/validators'>;
}
declare module 'giu/lib/gral/visibility.js' {
  declare module.exports: $Exports<'giu/lib/gral/visibility'>;
}
declare module 'giu/lib/hocs/hoverable.js' {
  declare module.exports: $Exports<'giu/lib/hocs/hoverable'>;
}
declare module 'giu/lib/hocs/input.js' {
  declare module.exports: $Exports<'giu/lib/hocs/input'>;
}
declare module 'giu/lib/index.js' {
  declare module.exports: $Exports<'giu/lib/index'>;
}
declare module 'giu/lib/inputs/checkbox.js' {
  declare module.exports: $Exports<'giu/lib/inputs/checkbox'>;
}
declare module 'giu/lib/inputs/colorInput.js' {
  declare module.exports: $Exports<'giu/lib/inputs/colorInput'>;
}
declare module 'giu/lib/inputs/colorPicker.js' {
  declare module.exports: $Exports<'giu/lib/inputs/colorPicker'>;
}
declare module 'giu/lib/inputs/dateInput.js' {
  declare module.exports: $Exports<'giu/lib/inputs/dateInput'>;
}
declare module 'giu/lib/inputs/datePicker.js' {
  declare module.exports: $Exports<'giu/lib/inputs/datePicker'>;
}
declare module 'giu/lib/inputs/dateTimePicker.js' {
  declare module.exports: $Exports<'giu/lib/inputs/dateTimePicker'>;
}
declare module 'giu/lib/inputs/fileInput.js' {
  declare module.exports: $Exports<'giu/lib/inputs/fileInput'>;
}
declare module 'giu/lib/inputs/iosFloatWrapper.js' {
  declare module.exports: $Exports<'giu/lib/inputs/iosFloatWrapper'>;
}
declare module 'giu/lib/inputs/listPicker.js' {
  declare module.exports: $Exports<'giu/lib/inputs/listPicker'>;
}
declare module 'giu/lib/inputs/radioGroup.js' {
  declare module.exports: $Exports<'giu/lib/inputs/radioGroup'>;
}
declare module 'giu/lib/inputs/select.js' {
  declare module.exports: $Exports<'giu/lib/inputs/select'>;
}
declare module 'giu/lib/inputs/selectCustom.js' {
  declare module.exports: $Exports<'giu/lib/inputs/selectCustom'>;
}
declare module 'giu/lib/inputs/selectNative.js' {
  declare module.exports: $Exports<'giu/lib/inputs/selectNative'>;
}
declare module 'giu/lib/inputs/textarea.js' {
  declare module.exports: $Exports<'giu/lib/inputs/textarea'>;
}
declare module 'giu/lib/inputs/textNumberRangeInput.js' {
  declare module.exports: $Exports<'giu/lib/inputs/textNumberRangeInput'>;
}
declare module 'giu/lib/inputs/timePickerAnalog.js' {
  declare module.exports: $Exports<'giu/lib/inputs/timePickerAnalog'>;
}
declare module 'giu/lib/inputs/timePickerDigital.js' {
  declare module.exports: $Exports<'giu/lib/inputs/timePickerDigital'>;
}
declare module 'giu/libEs6/components/backdrop.js' {
  declare module.exports: $Exports<'giu/libEs6/components/backdrop'>;
}
declare module 'giu/libEs6/components/button.js' {
  declare module.exports: $Exports<'giu/libEs6/components/button'>;
}
declare module 'giu/libEs6/components/dataTable.js' {
  declare module.exports: $Exports<'giu/libEs6/components/dataTable'>;
}
declare module 'giu/libEs6/components/dataTableRow.js' {
  declare module.exports: $Exports<'giu/libEs6/components/dataTableRow'>;
}
declare module 'giu/libEs6/components/dropDownMenu.js' {
  declare module.exports: $Exports<'giu/libEs6/components/dropDownMenu'>;
}
declare module 'giu/libEs6/components/floats.js' {
  declare module.exports: $Exports<'giu/libEs6/components/floats'>;
}
declare module 'giu/libEs6/components/focusCapture.js' {
  declare module.exports: $Exports<'giu/libEs6/components/focusCapture'>;
}
declare module 'giu/libEs6/components/hintArrow.js' {
  declare module.exports: $Exports<'giu/libEs6/components/hintArrow'>;
}
declare module 'giu/libEs6/components/hintLabel.js' {
  declare module.exports: $Exports<'giu/libEs6/components/hintLabel'>;
}
declare module 'giu/libEs6/components/hints.js' {
  declare module.exports: $Exports<'giu/libEs6/components/hints'>;
}
declare module 'giu/libEs6/components/hintScreen.js' {
  declare module.exports: $Exports<'giu/libEs6/components/hintScreen'>;
}
declare module 'giu/libEs6/components/icon.js' {
  declare module.exports: $Exports<'giu/libEs6/components/icon'>;
}
declare module 'giu/libEs6/components/largeMessage.js' {
  declare module.exports: $Exports<'giu/libEs6/components/largeMessage'>;
}
declare module 'giu/libEs6/components/modal.js' {
  declare module.exports: $Exports<'giu/libEs6/components/modal'>;
}
declare module 'giu/libEs6/components/modals.js' {
  declare module.exports: $Exports<'giu/libEs6/components/modals'>;
}
declare module 'giu/libEs6/components/notification.js' {
  declare module.exports: $Exports<'giu/libEs6/components/notification'>;
}
declare module 'giu/libEs6/components/notifications.js' {
  declare module.exports: $Exports<'giu/libEs6/components/notifications'>;
}
declare module 'giu/libEs6/components/progress.js' {
  declare module.exports: $Exports<'giu/libEs6/components/progress'>;
}
declare module 'giu/libEs6/components/spinner.js' {
  declare module.exports: $Exports<'giu/libEs6/components/spinner'>;
}
declare module 'giu/libEs6/components/verticalManager.js' {
  declare module.exports: $Exports<'giu/libEs6/components/verticalManager'>;
}
declare module 'giu/libEs6/components/virtualScroller.js' {
  declare module.exports: $Exports<'giu/libEs6/components/virtualScroller'>;
}
declare module 'giu/libEs6/gral/constants.js' {
  declare module.exports: $Exports<'giu/libEs6/gral/constants'>;
}
declare module 'giu/libEs6/gral/dates.js' {
  declare module.exports: $Exports<'giu/libEs6/gral/dates'>;
}
declare module 'giu/libEs6/gral/helpers.js' {
  declare module.exports: $Exports<'giu/libEs6/gral/helpers'>;
}
declare module 'giu/libEs6/gral/keys.js' {
  declare module.exports: $Exports<'giu/libEs6/gral/keys'>;
}
declare module 'giu/libEs6/gral/math.js' {
  declare module.exports: $Exports<'giu/libEs6/gral/math'>;
}
declare module 'giu/libEs6/gral/storage.js' {
  declare module.exports: $Exports<'giu/libEs6/gral/storage'>;
}
declare module 'giu/libEs6/gral/styles.js' {
  declare module.exports: $Exports<'giu/libEs6/gral/styles'>;
}
declare module 'giu/libEs6/gral/validators.js' {
  declare module.exports: $Exports<'giu/libEs6/gral/validators'>;
}
declare module 'giu/libEs6/gral/visibility.js' {
  declare module.exports: $Exports<'giu/libEs6/gral/visibility'>;
}
declare module 'giu/libEs6/hocs/hoverable.js' {
  declare module.exports: $Exports<'giu/libEs6/hocs/hoverable'>;
}
declare module 'giu/libEs6/hocs/input.js' {
  declare module.exports: $Exports<'giu/libEs6/hocs/input'>;
}
declare module 'giu/libEs6/index.js' {
  declare module.exports: $Exports<'giu/libEs6/index'>;
}
declare module 'giu/libEs6/inputs/checkbox.js' {
  declare module.exports: $Exports<'giu/libEs6/inputs/checkbox'>;
}
declare module 'giu/libEs6/inputs/colorInput.js' {
  declare module.exports: $Exports<'giu/libEs6/inputs/colorInput'>;
}
declare module 'giu/libEs6/inputs/colorPicker.js' {
  declare module.exports: $Exports<'giu/libEs6/inputs/colorPicker'>;
}
declare module 'giu/libEs6/inputs/dateInput.js' {
  declare module.exports: $Exports<'giu/libEs6/inputs/dateInput'>;
}
declare module 'giu/libEs6/inputs/datePicker.js' {
  declare module.exports: $Exports<'giu/libEs6/inputs/datePicker'>;
}
declare module 'giu/libEs6/inputs/dateTimePicker.js' {
  declare module.exports: $Exports<'giu/libEs6/inputs/dateTimePicker'>;
}
declare module 'giu/libEs6/inputs/fileInput.js' {
  declare module.exports: $Exports<'giu/libEs6/inputs/fileInput'>;
}
declare module 'giu/libEs6/inputs/iosFloatWrapper.js' {
  declare module.exports: $Exports<'giu/libEs6/inputs/iosFloatWrapper'>;
}
declare module 'giu/libEs6/inputs/listPicker.js' {
  declare module.exports: $Exports<'giu/libEs6/inputs/listPicker'>;
}
declare module 'giu/libEs6/inputs/radioGroup.js' {
  declare module.exports: $Exports<'giu/libEs6/inputs/radioGroup'>;
}
declare module 'giu/libEs6/inputs/select.js' {
  declare module.exports: $Exports<'giu/libEs6/inputs/select'>;
}
declare module 'giu/libEs6/inputs/selectCustom.js' {
  declare module.exports: $Exports<'giu/libEs6/inputs/selectCustom'>;
}
declare module 'giu/libEs6/inputs/selectNative.js' {
  declare module.exports: $Exports<'giu/libEs6/inputs/selectNative'>;
}
declare module 'giu/libEs6/inputs/textarea.js' {
  declare module.exports: $Exports<'giu/libEs6/inputs/textarea'>;
}
declare module 'giu/libEs6/inputs/textNumberRangeInput.js' {
  declare module.exports: $Exports<'giu/libEs6/inputs/textNumberRangeInput'>;
}
declare module 'giu/libEs6/inputs/timePickerAnalog.js' {
  declare module.exports: $Exports<'giu/libEs6/inputs/timePickerAnalog'>;
}
declare module 'giu/libEs6/inputs/timePickerDigital.js' {
  declare module.exports: $Exports<'giu/libEs6/inputs/timePickerDigital'>;
}
