// flow-typed signature: b732e7aadcfe870eeeac2ae7784bdda2
// flow-typed version: <<STUB>>/isomorphic-relay_v0.7.3/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'isomorphic-relay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'isomorphic-relay' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'isomorphic-relay/lib/index' {
  declare module.exports: any;
}

declare module 'isomorphic-relay/lib/injectPreparedData' {
  declare module.exports: any;
}

declare module 'isomorphic-relay/lib/IsomorphicRenderer' {
  declare module.exports: any;
}

declare module 'isomorphic-relay/lib/prepareData' {
  declare module.exports: any;
}

declare module 'isomorphic-relay/lib/prepareInitialRender' {
  declare module.exports: any;
}

// Filename aliases
declare module 'isomorphic-relay/lib/index.js' {
  declare module.exports: $Exports<'isomorphic-relay/lib/index'>;
}
declare module 'isomorphic-relay/lib/injectPreparedData.js' {
  declare module.exports: $Exports<'isomorphic-relay/lib/injectPreparedData'>;
}
declare module 'isomorphic-relay/lib/IsomorphicRenderer.js' {
  declare module.exports: $Exports<'isomorphic-relay/lib/IsomorphicRenderer'>;
}
declare module 'isomorphic-relay/lib/prepareData.js' {
  declare module.exports: $Exports<'isomorphic-relay/lib/prepareData'>;
}
declare module 'isomorphic-relay/lib/prepareInitialRender.js' {
  declare module.exports: $Exports<'isomorphic-relay/lib/prepareInitialRender'>;
}
