// flow-typed signature: 420c996991cfdd25ec0bd5b21eb4575b
// flow-typed version: <<STUB>>/messageformat_v1.0.2/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'messageformat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'messageformat' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'messageformat/bin/messageformat' {
  declare module.exports: any;
}

declare module 'messageformat/doc/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'messageformat/doc/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'messageformat/doc/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'messageformat/example/i18n' {
  declare module.exports: any;
}

declare module 'messageformat/lib/compiler' {
  declare module.exports: any;
}

declare module 'messageformat/lib/index' {
  declare module.exports: any;
}

declare module 'messageformat/lib/runtime' {
  declare module.exports: any;
}

declare module 'messageformat/messageformat' {
  declare module.exports: any;
}

declare module 'messageformat/messageformat.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'messageformat/bin/messageformat.js' {
  declare module.exports: $Exports<'messageformat/bin/messageformat'>;
}
declare module 'messageformat/doc/scripts/linenumber.js' {
  declare module.exports: $Exports<'messageformat/doc/scripts/linenumber'>;
}
declare module 'messageformat/doc/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'messageformat/doc/scripts/prettify/lang-css'>;
}
declare module 'messageformat/doc/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'messageformat/doc/scripts/prettify/prettify'>;
}
declare module 'messageformat/example/i18n.js' {
  declare module.exports: $Exports<'messageformat/example/i18n'>;
}
declare module 'messageformat/lib/compiler.js' {
  declare module.exports: $Exports<'messageformat/lib/compiler'>;
}
declare module 'messageformat/lib/index.js' {
  declare module.exports: $Exports<'messageformat/lib/index'>;
}
declare module 'messageformat/lib/runtime.js' {
  declare module.exports: $Exports<'messageformat/lib/runtime'>;
}
declare module 'messageformat/messageformat.js' {
  declare module.exports: $Exports<'messageformat/messageformat'>;
}
declare module 'messageformat/messageformat.min.js' {
  declare module.exports: $Exports<'messageformat/messageformat.min'>;
}
