// flow-typed signature: 8657ee020d0a97a9f6b0f2d1760d6c08
// flow-typed version: <<STUB>>/react-relay_v0.9.3/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-relay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-relay' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-relay/dist/relay' {
  declare module.exports: any;
}

declare module 'react-relay/dist/relay.min' {
  declare module.exports: any;
}

declare module 'react-relay/lib/buildRQL' {
  declare module.exports: any;
}

declare module 'react-relay/lib/callsFromGraphQL' {
  declare module.exports: any;
}

declare module 'react-relay/lib/callsToGraphQL' {
  declare module.exports: any;
}

declare module 'react-relay/lib/checkRelayQueryData' {
  declare module.exports: any;
}

declare module 'react-relay/lib/ConcreteQuery' {
  declare module.exports: any;
}

declare module 'react-relay/lib/containsRelayQueryRootCall' {
  declare module.exports: any;
}

declare module 'react-relay/lib/createRelayQuery' {
  declare module.exports: any;
}

declare module 'react-relay/lib/dedent' {
  declare module.exports: any;
}

declare module 'react-relay/lib/diffRelayQuery' {
  declare module.exports: any;
}

declare module 'react-relay/lib/directivesToGraphQL' {
  declare module.exports: any;
}

declare module 'react-relay/lib/filterExclusiveKeys' {
  declare module.exports: any;
}

declare module 'react-relay/lib/filterRelayQuery' {
  declare module.exports: any;
}

declare module 'react-relay/lib/findRelayQueryLeaves' {
  declare module.exports: any;
}

declare module 'react-relay/lib/flattenRelayQuery' {
  declare module.exports: any;
}

declare module 'react-relay/lib/flattenSplitRelayQueries' {
  declare module.exports: any;
}

declare module 'react-relay/lib/forEachRootCallArg' {
  declare module.exports: any;
}

declare module 'react-relay/lib/fromGraphQL' {
  declare module.exports: any;
}

declare module 'react-relay/lib/generateClientEdgeID' {
  declare module.exports: any;
}

declare module 'react-relay/lib/generateClientID' {
  declare module.exports: any;
}

declare module 'react-relay/lib/generateConcreteFragmentID' {
  declare module.exports: any;
}

declare module 'react-relay/lib/generateForceIndex' {
  declare module.exports: any;
}

declare module 'react-relay/lib/generateRQLFieldAlias' {
  declare module.exports: any;
}

declare module 'react-relay/lib/getRangeBehavior' {
  declare module.exports: any;
}

declare module 'react-relay/lib/getRelayQueries' {
  declare module.exports: any;
}

declare module 'react-relay/lib/GraphQLMutatorConstants' {
  declare module.exports: any;
}

declare module 'react-relay/lib/GraphQLQueryRunner' {
  declare module.exports: any;
}

declare module 'react-relay/lib/GraphQLRange' {
  declare module.exports: any;
}

declare module 'react-relay/lib/GraphQLSegment' {
  declare module.exports: any;
}

declare module 'react-relay/lib/GraphQLStoreChangeEmitter' {
  declare module.exports: any;
}

declare module 'react-relay/lib/GraphQLStoreQueryResolver' {
  declare module.exports: any;
}

declare module 'react-relay/lib/GraphQLStoreRangeUtils' {
  declare module.exports: any;
}

declare module 'react-relay/lib/intersectRelayQuery' {
  declare module.exports: any;
}

declare module 'react-relay/lib/isCompatibleRelayFragmentType' {
  declare module.exports: any;
}

declare module 'react-relay/lib/isRelayContainer' {
  declare module.exports: any;
}

declare module 'react-relay/lib/isRelayEnvironment' {
  declare module.exports: any;
}

declare module 'react-relay/lib/printRelayOSSQuery' {
  declare module.exports: any;
}

declare module 'react-relay/lib/printRelayQuery' {
  declare module.exports: any;
}

declare module 'react-relay/lib/QueryBuilder' {
  declare module.exports: any;
}

declare module 'react-relay/lib/rangeOperationToMetadataKey' {
  declare module.exports: any;
}

declare module 'react-relay/lib/readRelayQueryData' {
  declare module.exports: any;
}

declare module 'react-relay/lib/recycleNodesInto' {
  declare module.exports: any;
}

declare module 'react-relay/lib/Relay' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayCacheProcessor' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayChangeTracker' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayConnectionInterface' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayContainer' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayContainerComparators' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayContainerProxy' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayContainerUtils' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayDefaultNetworkLayer' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayEnvironment' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayEnvironmentSerializer' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayError' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayFetchMode' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayFragmentPointer' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayFragmentReference' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayGarbageCollection' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayGarbageCollector' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayGraphModeInterface' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayGraphQLMutation' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayInternals' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayInternalTypes' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayMetaRoute' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayMetricsRecorder' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayMutation' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayMutationDebugPrinter' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayMutationQuery' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayMutationQueue' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayMutationRequest' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayMutationTracker' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayMutationTransaction' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayMutationTransactionStatus' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayMutationType' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayNetworkDebug' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayNetworkLayer' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayNodeInterface' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayOptimisticMutationUtils' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayOSSConnectionInterface' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayOSSContainerProxy' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayOSSNodeInterface' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayPendingQueryTracker' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayProfiler' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayPropTypes' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayPublic' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayQL' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayQuery' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayQueryCaching' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayQueryConfig' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayQueryPath' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayQueryRequest' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayQueryResultObservable' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayQueryTracker' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayQueryTransform' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayQueryVisitor' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayQueryWriter' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayReadyState' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayReadyStateRenderer' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayRecord' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayRecordState' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayRecordStatusMap' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayRecordStore' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayRecordWriter' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayRefQueryDescriptor' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayRenderer' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayRootContainer' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayRoute' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayRouteFragment' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayStore' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayStoreData' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayTaskQueue' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayTypes' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relayUnstableBatchedUpdates' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relayUnstableBatchedUpdates.native' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayVariable' {
  declare module.exports: any;
}

declare module 'react-relay/lib/restoreRelayCacheData' {
  declare module.exports: any;
}

declare module 'react-relay/lib/serializeRelayQueryCall' {
  declare module.exports: any;
}

declare module 'react-relay/lib/sortTypeFirst' {
  declare module.exports: any;
}

declare module 'react-relay/lib/splitDeferredRelayQueries' {
  declare module.exports: any;
}

declare module 'react-relay/lib/stableStringify' {
  declare module.exports: any;
}

declare module 'react-relay/lib/testEditDistance' {
  declare module.exports: any;
}

declare module 'react-relay/lib/toGraphQL' {
  declare module.exports: any;
}

declare module 'react-relay/lib/transformPayloadToRelayGraphMode' {
  declare module.exports: any;
}

declare module 'react-relay/lib/transformRelayQueryPayload' {
  declare module.exports: any;
}

declare module 'react-relay/lib/validateMutationConfig' {
  declare module.exports: any;
}

declare module 'react-relay/lib/validateRelayReadQuery' {
  declare module.exports: any;
}

declare module 'react-relay/lib/writeRelayGraphModeResponse' {
  declare module.exports: any;
}

declare module 'react-relay/lib/writeRelayQueryPayload' {
  declare module.exports: any;
}

declare module 'react-relay/lib/writeRelayUpdatePayload' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-relay/dist/relay.js' {
  declare module.exports: $Exports<'react-relay/dist/relay'>;
}
declare module 'react-relay/dist/relay.min.js' {
  declare module.exports: $Exports<'react-relay/dist/relay.min'>;
}
declare module 'react-relay/lib/buildRQL.js' {
  declare module.exports: $Exports<'react-relay/lib/buildRQL'>;
}
declare module 'react-relay/lib/callsFromGraphQL.js' {
  declare module.exports: $Exports<'react-relay/lib/callsFromGraphQL'>;
}
declare module 'react-relay/lib/callsToGraphQL.js' {
  declare module.exports: $Exports<'react-relay/lib/callsToGraphQL'>;
}
declare module 'react-relay/lib/checkRelayQueryData.js' {
  declare module.exports: $Exports<'react-relay/lib/checkRelayQueryData'>;
}
declare module 'react-relay/lib/ConcreteQuery.js' {
  declare module.exports: $Exports<'react-relay/lib/ConcreteQuery'>;
}
declare module 'react-relay/lib/containsRelayQueryRootCall.js' {
  declare module.exports: $Exports<'react-relay/lib/containsRelayQueryRootCall'>;
}
declare module 'react-relay/lib/createRelayQuery.js' {
  declare module.exports: $Exports<'react-relay/lib/createRelayQuery'>;
}
declare module 'react-relay/lib/dedent.js' {
  declare module.exports: $Exports<'react-relay/lib/dedent'>;
}
declare module 'react-relay/lib/diffRelayQuery.js' {
  declare module.exports: $Exports<'react-relay/lib/diffRelayQuery'>;
}
declare module 'react-relay/lib/directivesToGraphQL.js' {
  declare module.exports: $Exports<'react-relay/lib/directivesToGraphQL'>;
}
declare module 'react-relay/lib/filterExclusiveKeys.js' {
  declare module.exports: $Exports<'react-relay/lib/filterExclusiveKeys'>;
}
declare module 'react-relay/lib/filterRelayQuery.js' {
  declare module.exports: $Exports<'react-relay/lib/filterRelayQuery'>;
}
declare module 'react-relay/lib/findRelayQueryLeaves.js' {
  declare module.exports: $Exports<'react-relay/lib/findRelayQueryLeaves'>;
}
declare module 'react-relay/lib/flattenRelayQuery.js' {
  declare module.exports: $Exports<'react-relay/lib/flattenRelayQuery'>;
}
declare module 'react-relay/lib/flattenSplitRelayQueries.js' {
  declare module.exports: $Exports<'react-relay/lib/flattenSplitRelayQueries'>;
}
declare module 'react-relay/lib/forEachRootCallArg.js' {
  declare module.exports: $Exports<'react-relay/lib/forEachRootCallArg'>;
}
declare module 'react-relay/lib/fromGraphQL.js' {
  declare module.exports: $Exports<'react-relay/lib/fromGraphQL'>;
}
declare module 'react-relay/lib/generateClientEdgeID.js' {
  declare module.exports: $Exports<'react-relay/lib/generateClientEdgeID'>;
}
declare module 'react-relay/lib/generateClientID.js' {
  declare module.exports: $Exports<'react-relay/lib/generateClientID'>;
}
declare module 'react-relay/lib/generateConcreteFragmentID.js' {
  declare module.exports: $Exports<'react-relay/lib/generateConcreteFragmentID'>;
}
declare module 'react-relay/lib/generateForceIndex.js' {
  declare module.exports: $Exports<'react-relay/lib/generateForceIndex'>;
}
declare module 'react-relay/lib/generateRQLFieldAlias.js' {
  declare module.exports: $Exports<'react-relay/lib/generateRQLFieldAlias'>;
}
declare module 'react-relay/lib/getRangeBehavior.js' {
  declare module.exports: $Exports<'react-relay/lib/getRangeBehavior'>;
}
declare module 'react-relay/lib/getRelayQueries.js' {
  declare module.exports: $Exports<'react-relay/lib/getRelayQueries'>;
}
declare module 'react-relay/lib/GraphQLMutatorConstants.js' {
  declare module.exports: $Exports<'react-relay/lib/GraphQLMutatorConstants'>;
}
declare module 'react-relay/lib/GraphQLQueryRunner.js' {
  declare module.exports: $Exports<'react-relay/lib/GraphQLQueryRunner'>;
}
declare module 'react-relay/lib/GraphQLRange.js' {
  declare module.exports: $Exports<'react-relay/lib/GraphQLRange'>;
}
declare module 'react-relay/lib/GraphQLSegment.js' {
  declare module.exports: $Exports<'react-relay/lib/GraphQLSegment'>;
}
declare module 'react-relay/lib/GraphQLStoreChangeEmitter.js' {
  declare module.exports: $Exports<'react-relay/lib/GraphQLStoreChangeEmitter'>;
}
declare module 'react-relay/lib/GraphQLStoreQueryResolver.js' {
  declare module.exports: $Exports<'react-relay/lib/GraphQLStoreQueryResolver'>;
}
declare module 'react-relay/lib/GraphQLStoreRangeUtils.js' {
  declare module.exports: $Exports<'react-relay/lib/GraphQLStoreRangeUtils'>;
}
declare module 'react-relay/lib/intersectRelayQuery.js' {
  declare module.exports: $Exports<'react-relay/lib/intersectRelayQuery'>;
}
declare module 'react-relay/lib/isCompatibleRelayFragmentType.js' {
  declare module.exports: $Exports<'react-relay/lib/isCompatibleRelayFragmentType'>;
}
declare module 'react-relay/lib/isRelayContainer.js' {
  declare module.exports: $Exports<'react-relay/lib/isRelayContainer'>;
}
declare module 'react-relay/lib/isRelayEnvironment.js' {
  declare module.exports: $Exports<'react-relay/lib/isRelayEnvironment'>;
}
declare module 'react-relay/lib/printRelayOSSQuery.js' {
  declare module.exports: $Exports<'react-relay/lib/printRelayOSSQuery'>;
}
declare module 'react-relay/lib/printRelayQuery.js' {
  declare module.exports: $Exports<'react-relay/lib/printRelayQuery'>;
}
declare module 'react-relay/lib/QueryBuilder.js' {
  declare module.exports: $Exports<'react-relay/lib/QueryBuilder'>;
}
declare module 'react-relay/lib/rangeOperationToMetadataKey.js' {
  declare module.exports: $Exports<'react-relay/lib/rangeOperationToMetadataKey'>;
}
declare module 'react-relay/lib/readRelayQueryData.js' {
  declare module.exports: $Exports<'react-relay/lib/readRelayQueryData'>;
}
declare module 'react-relay/lib/recycleNodesInto.js' {
  declare module.exports: $Exports<'react-relay/lib/recycleNodesInto'>;
}
declare module 'react-relay/lib/Relay.js' {
  declare module.exports: $Exports<'react-relay/lib/Relay'>;
}
declare module 'react-relay/lib/RelayCacheProcessor.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayCacheProcessor'>;
}
declare module 'react-relay/lib/RelayChangeTracker.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayChangeTracker'>;
}
declare module 'react-relay/lib/RelayConnectionInterface.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayConnectionInterface'>;
}
declare module 'react-relay/lib/RelayContainer.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayContainer'>;
}
declare module 'react-relay/lib/RelayContainerComparators.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayContainerComparators'>;
}
declare module 'react-relay/lib/RelayContainerProxy.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayContainerProxy'>;
}
declare module 'react-relay/lib/RelayContainerUtils.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayContainerUtils'>;
}
declare module 'react-relay/lib/RelayDefaultNetworkLayer.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayDefaultNetworkLayer'>;
}
declare module 'react-relay/lib/RelayEnvironment.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayEnvironment'>;
}
declare module 'react-relay/lib/RelayEnvironmentSerializer.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayEnvironmentSerializer'>;
}
declare module 'react-relay/lib/RelayError.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayError'>;
}
declare module 'react-relay/lib/RelayFetchMode.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayFetchMode'>;
}
declare module 'react-relay/lib/RelayFragmentPointer.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayFragmentPointer'>;
}
declare module 'react-relay/lib/RelayFragmentReference.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayFragmentReference'>;
}
declare module 'react-relay/lib/RelayGarbageCollection.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayGarbageCollection'>;
}
declare module 'react-relay/lib/RelayGarbageCollector.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayGarbageCollector'>;
}
declare module 'react-relay/lib/RelayGraphModeInterface.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayGraphModeInterface'>;
}
declare module 'react-relay/lib/RelayGraphQLMutation.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayGraphQLMutation'>;
}
declare module 'react-relay/lib/RelayInternals.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayInternals'>;
}
declare module 'react-relay/lib/RelayInternalTypes.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayInternalTypes'>;
}
declare module 'react-relay/lib/RelayMetaRoute.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayMetaRoute'>;
}
declare module 'react-relay/lib/RelayMetricsRecorder.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayMetricsRecorder'>;
}
declare module 'react-relay/lib/RelayMutation.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayMutation'>;
}
declare module 'react-relay/lib/RelayMutationDebugPrinter.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayMutationDebugPrinter'>;
}
declare module 'react-relay/lib/RelayMutationQuery.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayMutationQuery'>;
}
declare module 'react-relay/lib/RelayMutationQueue.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayMutationQueue'>;
}
declare module 'react-relay/lib/RelayMutationRequest.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayMutationRequest'>;
}
declare module 'react-relay/lib/RelayMutationTracker.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayMutationTracker'>;
}
declare module 'react-relay/lib/RelayMutationTransaction.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayMutationTransaction'>;
}
declare module 'react-relay/lib/RelayMutationTransactionStatus.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayMutationTransactionStatus'>;
}
declare module 'react-relay/lib/RelayMutationType.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayMutationType'>;
}
declare module 'react-relay/lib/RelayNetworkDebug.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayNetworkDebug'>;
}
declare module 'react-relay/lib/RelayNetworkLayer.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayNetworkLayer'>;
}
declare module 'react-relay/lib/RelayNodeInterface.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayNodeInterface'>;
}
declare module 'react-relay/lib/RelayOptimisticMutationUtils.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayOptimisticMutationUtils'>;
}
declare module 'react-relay/lib/RelayOSSConnectionInterface.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayOSSConnectionInterface'>;
}
declare module 'react-relay/lib/RelayOSSContainerProxy.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayOSSContainerProxy'>;
}
declare module 'react-relay/lib/RelayOSSNodeInterface.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayOSSNodeInterface'>;
}
declare module 'react-relay/lib/RelayPendingQueryTracker.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayPendingQueryTracker'>;
}
declare module 'react-relay/lib/RelayProfiler.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayProfiler'>;
}
declare module 'react-relay/lib/RelayPropTypes.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayPropTypes'>;
}
declare module 'react-relay/lib/RelayPublic.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayPublic'>;
}
declare module 'react-relay/lib/RelayQL.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayQL'>;
}
declare module 'react-relay/lib/RelayQuery.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayQuery'>;
}
declare module 'react-relay/lib/RelayQueryCaching.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayQueryCaching'>;
}
declare module 'react-relay/lib/RelayQueryConfig.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayQueryConfig'>;
}
declare module 'react-relay/lib/RelayQueryPath.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayQueryPath'>;
}
declare module 'react-relay/lib/RelayQueryRequest.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayQueryRequest'>;
}
declare module 'react-relay/lib/RelayQueryResultObservable.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayQueryResultObservable'>;
}
declare module 'react-relay/lib/RelayQueryTracker.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayQueryTracker'>;
}
declare module 'react-relay/lib/RelayQueryTransform.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayQueryTransform'>;
}
declare module 'react-relay/lib/RelayQueryVisitor.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayQueryVisitor'>;
}
declare module 'react-relay/lib/RelayQueryWriter.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayQueryWriter'>;
}
declare module 'react-relay/lib/RelayReadyState.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayReadyState'>;
}
declare module 'react-relay/lib/RelayReadyStateRenderer.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayReadyStateRenderer'>;
}
declare module 'react-relay/lib/RelayRecord.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayRecord'>;
}
declare module 'react-relay/lib/RelayRecordState.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayRecordState'>;
}
declare module 'react-relay/lib/RelayRecordStatusMap.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayRecordStatusMap'>;
}
declare module 'react-relay/lib/RelayRecordStore.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayRecordStore'>;
}
declare module 'react-relay/lib/RelayRecordWriter.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayRecordWriter'>;
}
declare module 'react-relay/lib/RelayRefQueryDescriptor.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayRefQueryDescriptor'>;
}
declare module 'react-relay/lib/RelayRenderer.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayRenderer'>;
}
declare module 'react-relay/lib/RelayRootContainer.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayRootContainer'>;
}
declare module 'react-relay/lib/RelayRoute.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayRoute'>;
}
declare module 'react-relay/lib/RelayRouteFragment.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayRouteFragment'>;
}
declare module 'react-relay/lib/RelayStore.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayStore'>;
}
declare module 'react-relay/lib/RelayStoreData.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayStoreData'>;
}
declare module 'react-relay/lib/RelayTaskQueue.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayTaskQueue'>;
}
declare module 'react-relay/lib/RelayTypes.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayTypes'>;
}
declare module 'react-relay/lib/relayUnstableBatchedUpdates.js' {
  declare module.exports: $Exports<'react-relay/lib/relayUnstableBatchedUpdates'>;
}
declare module 'react-relay/lib/relayUnstableBatchedUpdates.native.js' {
  declare module.exports: $Exports<'react-relay/lib/relayUnstableBatchedUpdates.native'>;
}
declare module 'react-relay/lib/RelayVariable.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayVariable'>;
}
declare module 'react-relay/lib/restoreRelayCacheData.js' {
  declare module.exports: $Exports<'react-relay/lib/restoreRelayCacheData'>;
}
declare module 'react-relay/lib/serializeRelayQueryCall.js' {
  declare module.exports: $Exports<'react-relay/lib/serializeRelayQueryCall'>;
}
declare module 'react-relay/lib/sortTypeFirst.js' {
  declare module.exports: $Exports<'react-relay/lib/sortTypeFirst'>;
}
declare module 'react-relay/lib/splitDeferredRelayQueries.js' {
  declare module.exports: $Exports<'react-relay/lib/splitDeferredRelayQueries'>;
}
declare module 'react-relay/lib/stableStringify.js' {
  declare module.exports: $Exports<'react-relay/lib/stableStringify'>;
}
declare module 'react-relay/lib/testEditDistance.js' {
  declare module.exports: $Exports<'react-relay/lib/testEditDistance'>;
}
declare module 'react-relay/lib/toGraphQL.js' {
  declare module.exports: $Exports<'react-relay/lib/toGraphQL'>;
}
declare module 'react-relay/lib/transformPayloadToRelayGraphMode.js' {
  declare module.exports: $Exports<'react-relay/lib/transformPayloadToRelayGraphMode'>;
}
declare module 'react-relay/lib/transformRelayQueryPayload.js' {
  declare module.exports: $Exports<'react-relay/lib/transformRelayQueryPayload'>;
}
declare module 'react-relay/lib/validateMutationConfig.js' {
  declare module.exports: $Exports<'react-relay/lib/validateMutationConfig'>;
}
declare module 'react-relay/lib/validateRelayReadQuery.js' {
  declare module.exports: $Exports<'react-relay/lib/validateRelayReadQuery'>;
}
declare module 'react-relay/lib/writeRelayGraphModeResponse.js' {
  declare module.exports: $Exports<'react-relay/lib/writeRelayGraphModeResponse'>;
}
declare module 'react-relay/lib/writeRelayQueryPayload.js' {
  declare module.exports: $Exports<'react-relay/lib/writeRelayQueryPayload'>;
}
declare module 'react-relay/lib/writeRelayUpdatePayload.js' {
  declare module.exports: $Exports<'react-relay/lib/writeRelayUpdatePayload'>;
}
