// flow-typed signature: 97c9f4fcf6b67a1ffb4aebf4c4a5bd3f
// flow-typed version: <<STUB>>/storyboard_v2.1.2/flow_v0.32.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storyboard'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'storyboard' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'storyboard/chromeExtension/background' {
  declare module.exports: any;
}

declare module 'storyboard/chromeExtension/contentScript' {
  declare module.exports: any;
}

declare module 'storyboard/chromeExtension/devPanel' {
  declare module.exports: any;
}

declare module 'storyboard/chromeExtension/devTools' {
  declare module.exports: any;
}

declare module 'storyboard/chromeExtension/devToolsApp' {
  declare module.exports: any;
}

declare module 'storyboard/example/app' {
  declare module.exports: any;
}

declare module 'storyboard/example/exampleUpload' {
  declare module.exports: any;
}

declare module 'storyboard/lib/cli' {
  declare module.exports: any;
}

declare module 'storyboard/lib/example/client' {
  declare module.exports: any;
}

declare module 'storyboard/lib/example/clientWithUpload' {
  declare module.exports: any;
}

declare module 'storyboard/lib/example/db' {
  declare module.exports: any;
}

declare module 'storyboard/lib/example/httpServer' {
  declare module.exports: any;
}

declare module 'storyboard/lib/example/server' {
  declare module.exports: any;
}

declare module 'storyboard/lib/example/serverWithDb' {
  declare module.exports: any;
}

declare module 'storyboard/lib/example/webpackConfig' {
  declare module.exports: any;
}

declare module 'storyboard/lib/example/writeSomeLogs' {
  declare module.exports: any;
}

declare module 'storyboard/lib/gral/ansiColors' {
  declare module.exports: any;
}

declare module 'storyboard/lib/gral/constants' {
  declare module.exports: any;
}

declare module 'storyboard/lib/gral/filters' {
  declare module.exports: any;
}

declare module 'storyboard/lib/gral/hub' {
  declare module.exports: any;
}

declare module 'storyboard/lib/gral/serialize' {
  declare module.exports: any;
}

declare module 'storyboard/lib/gral/stories' {
  declare module.exports: any;
}

declare module 'storyboard/lib/gral/treeLines' {
  declare module.exports: any;
}

declare module 'storyboard/lib/listeners/browserExtension' {
  declare module.exports: any;
}

declare module 'storyboard/lib/listeners/console' {
  declare module.exports: any;
}

declare module 'storyboard/lib/listeners/dbPostgres' {
  declare module.exports: any;
}

declare module 'storyboard/lib/listeners/file' {
  declare module.exports: any;
}

declare module 'storyboard/lib/listeners/helpers/recordToLines' {
  declare module.exports: any;
}

declare module 'storyboard/lib/listeners/wsClient' {
  declare module.exports: any;
}

declare module 'storyboard/lib/listeners/wsServer' {
  declare module.exports: any;
}

declare module 'storyboard/lib/noPlugins' {
  declare module.exports: any;
}

declare module 'storyboard/lib/serverLogsApp/app' {
  declare module.exports: any;
}

declare module 'storyboard/lib/serverLogsApp/webpackConfig' {
  declare module.exports: any;
}

declare module 'storyboard/lib/stdinLogger' {
  declare module.exports: any;
}

declare module 'storyboard/lib/storyboard' {
  declare module.exports: any;
}

declare module 'storyboard/lib/vendor/lodash' {
  declare module.exports: any;
}

declare module 'storyboard/lib/webpackConfigBase' {
  declare module.exports: any;
}

declare module 'storyboard/lib/withConsoleListener' {
  declare module.exports: any;
}

declare module 'storyboard/package' {
  declare module.exports: any;
}

declare module 'storyboard/serverLogsApp/app' {
  declare module.exports: any;
}

// Filename aliases
declare module 'storyboard/chromeExtension/background.js' {
  declare module.exports: $Exports<'storyboard/chromeExtension/background'>;
}
declare module 'storyboard/chromeExtension/contentScript.js' {
  declare module.exports: $Exports<'storyboard/chromeExtension/contentScript'>;
}
declare module 'storyboard/chromeExtension/devPanel.js' {
  declare module.exports: $Exports<'storyboard/chromeExtension/devPanel'>;
}
declare module 'storyboard/chromeExtension/devTools.js' {
  declare module.exports: $Exports<'storyboard/chromeExtension/devTools'>;
}
declare module 'storyboard/chromeExtension/devToolsApp.js' {
  declare module.exports: $Exports<'storyboard/chromeExtension/devToolsApp'>;
}
declare module 'storyboard/example/app.js' {
  declare module.exports: $Exports<'storyboard/example/app'>;
}
declare module 'storyboard/example/exampleUpload.js' {
  declare module.exports: $Exports<'storyboard/example/exampleUpload'>;
}
declare module 'storyboard/lib/cli.js' {
  declare module.exports: $Exports<'storyboard/lib/cli'>;
}
declare module 'storyboard/lib/example/client.js' {
  declare module.exports: $Exports<'storyboard/lib/example/client'>;
}
declare module 'storyboard/lib/example/clientWithUpload.js' {
  declare module.exports: $Exports<'storyboard/lib/example/clientWithUpload'>;
}
declare module 'storyboard/lib/example/db.js' {
  declare module.exports: $Exports<'storyboard/lib/example/db'>;
}
declare module 'storyboard/lib/example/httpServer.js' {
  declare module.exports: $Exports<'storyboard/lib/example/httpServer'>;
}
declare module 'storyboard/lib/example/server.js' {
  declare module.exports: $Exports<'storyboard/lib/example/server'>;
}
declare module 'storyboard/lib/example/serverWithDb.js' {
  declare module.exports: $Exports<'storyboard/lib/example/serverWithDb'>;
}
declare module 'storyboard/lib/example/webpackConfig.js' {
  declare module.exports: $Exports<'storyboard/lib/example/webpackConfig'>;
}
declare module 'storyboard/lib/example/writeSomeLogs.js' {
  declare module.exports: $Exports<'storyboard/lib/example/writeSomeLogs'>;
}
declare module 'storyboard/lib/gral/ansiColors.js' {
  declare module.exports: $Exports<'storyboard/lib/gral/ansiColors'>;
}
declare module 'storyboard/lib/gral/constants.js' {
  declare module.exports: $Exports<'storyboard/lib/gral/constants'>;
}
declare module 'storyboard/lib/gral/filters.js' {
  declare module.exports: $Exports<'storyboard/lib/gral/filters'>;
}
declare module 'storyboard/lib/gral/hub.js' {
  declare module.exports: $Exports<'storyboard/lib/gral/hub'>;
}
declare module 'storyboard/lib/gral/serialize.js' {
  declare module.exports: $Exports<'storyboard/lib/gral/serialize'>;
}
declare module 'storyboard/lib/gral/stories.js' {
  declare module.exports: $Exports<'storyboard/lib/gral/stories'>;
}
declare module 'storyboard/lib/gral/treeLines.js' {
  declare module.exports: $Exports<'storyboard/lib/gral/treeLines'>;
}
declare module 'storyboard/lib/listeners/browserExtension.js' {
  declare module.exports: $Exports<'storyboard/lib/listeners/browserExtension'>;
}
declare module 'storyboard/lib/listeners/console.js' {
  declare module.exports: $Exports<'storyboard/lib/listeners/console'>;
}
declare module 'storyboard/lib/listeners/dbPostgres.js' {
  declare module.exports: $Exports<'storyboard/lib/listeners/dbPostgres'>;
}
declare module 'storyboard/lib/listeners/file.js' {
  declare module.exports: $Exports<'storyboard/lib/listeners/file'>;
}
declare module 'storyboard/lib/listeners/helpers/recordToLines.js' {
  declare module.exports: $Exports<'storyboard/lib/listeners/helpers/recordToLines'>;
}
declare module 'storyboard/lib/listeners/wsClient.js' {
  declare module.exports: $Exports<'storyboard/lib/listeners/wsClient'>;
}
declare module 'storyboard/lib/listeners/wsServer.js' {
  declare module.exports: $Exports<'storyboard/lib/listeners/wsServer'>;
}
declare module 'storyboard/lib/noPlugins.js' {
  declare module.exports: $Exports<'storyboard/lib/noPlugins'>;
}
declare module 'storyboard/lib/serverLogsApp/app.js' {
  declare module.exports: $Exports<'storyboard/lib/serverLogsApp/app'>;
}
declare module 'storyboard/lib/serverLogsApp/webpackConfig.js' {
  declare module.exports: $Exports<'storyboard/lib/serverLogsApp/webpackConfig'>;
}
declare module 'storyboard/lib/stdinLogger.js' {
  declare module.exports: $Exports<'storyboard/lib/stdinLogger'>;
}
declare module 'storyboard/lib/storyboard.js' {
  declare module.exports: $Exports<'storyboard/lib/storyboard'>;
}
declare module 'storyboard/lib/vendor/lodash.js' {
  declare module.exports: $Exports<'storyboard/lib/vendor/lodash'>;
}
declare module 'storyboard/lib/webpackConfigBase.js' {
  declare module.exports: $Exports<'storyboard/lib/webpackConfigBase'>;
}
declare module 'storyboard/lib/withConsoleListener.js' {
  declare module.exports: $Exports<'storyboard/lib/withConsoleListener'>;
}
declare module 'storyboard/package.js' {
  declare module.exports: $Exports<'storyboard/package'>;
}
declare module 'storyboard/serverLogsApp/app.js' {
  declare module.exports: $Exports<'storyboard/serverLogsApp/app'>;
}
