// flow-typed signature: 12fb97ea25544fe56f6ff70a0a5ed682
// flow-typed version: <<STUB>>/tiny-cookie_v0.5.5/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tiny-cookie'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'tiny-cookie' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tiny-cookie/external/jasmine/1.3.1/jasmine-html' {
  declare module.exports: any;
}

declare module 'tiny-cookie/external/jasmine/1.3.1/jasmine' {
  declare module.exports: any;
}

declare module 'tiny-cookie/gulpfile' {
  declare module.exports: any;
}

declare module 'tiny-cookie/test/test' {
  declare module.exports: any;
}

declare module 'tiny-cookie/tiny-cookie' {
  declare module.exports: any;
}

declare module 'tiny-cookie/tiny-cookie.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tiny-cookie/external/jasmine/1.3.1/jasmine-html.js' {
  declare module.exports: $Exports<'tiny-cookie/external/jasmine/1.3.1/jasmine-html'>;
}
declare module 'tiny-cookie/external/jasmine/1.3.1/jasmine.js' {
  declare module.exports: $Exports<'tiny-cookie/external/jasmine/1.3.1/jasmine'>;
}
declare module 'tiny-cookie/gulpfile.js' {
  declare module.exports: $Exports<'tiny-cookie/gulpfile'>;
}
declare module 'tiny-cookie/test/test.js' {
  declare module.exports: $Exports<'tiny-cookie/test/test'>;
}
declare module 'tiny-cookie/tiny-cookie.js' {
  declare module.exports: $Exports<'tiny-cookie/tiny-cookie'>;
}
declare module 'tiny-cookie/tiny-cookie.min.js' {
  declare module.exports: $Exports<'tiny-cookie/tiny-cookie.min'>;
}
