// flow-typed signature: 4e5edd2c5ef7a1242e849bba00cdc02a
// flow-typed version: <<STUB>>/xxl_v0.1.1/flow_v0.32.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xxl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'xxl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'xxl/lib/xxl' {
  declare module.exports: any;
}

declare module 'xxl/libEs6_flow/xxl' {
  declare module.exports: any;
}

declare module 'xxl/libEs6/xxl' {
  declare module.exports: any;
}

// Filename aliases
declare module 'xxl/lib/xxl.js' {
  declare module.exports: $Exports<'xxl/lib/xxl'>;
}
declare module 'xxl/libEs6_flow/xxl.js' {
  declare module.exports: $Exports<'xxl/libEs6_flow/xxl'>;
}
declare module 'xxl/libEs6/xxl.js' {
  declare module.exports: $Exports<'xxl/libEs6/xxl'>;
}
